# Use the official Nginx image
FROM nginx:latest

# Set the working directory for serving files
WORKDIR /app

# Copy everything from the build context (client directory)
COPY ./client /app

# Update Nginx configuration to serve files from /app
RUN sed -i 's|/usr/share/nginx/html|/app|g' /etc/nginx/conf.d/default.conf

# Expose the port that Nginx uses
EXPOSE 80

# Default command to start Nginx
CMD ["nginx", "-g", "daemon off;"]

# FROM nginx:latest
# COPY html/ /usr/share/nginx/html/
# COPY css/ /usr/share/nginx/html/css/
# COPY js/ /usr/share/nginx/html/js/
# EXPOSE 80