# Generated by Django 4.2.11 on 2024-12-22 16:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPDAL', '0003_matchhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchHistory',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profiledata',
            name='friendList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='profiledata',
            name='winRate',
            field=models.FloatField(default=0.0),
        ),
    ]
