# Generated by Django 4.2.11 on 2024-12-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPDAL', '0006_verificationcode_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='password',
            field=models.CharField(blank=True, null=True),
        ),
    ]
