# Generated by Django 4.2.11 on 2024-12-28 08:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPDAL', '0007_verificationcode_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('pendingRequests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
            ],
        ),
    ]
