# Generated by Django 4.2.11 on 2025-01-19 17:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPDAL', '0010_alter_profiledata_displayname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='pendingRequests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
