# Generated by Django 4.2.11 on 2025-01-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BPDAL', '0010_alter_profiledata_displayname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledata',
            name='displayName',
            field=models.CharField(default=models.CharField(max_length=100, unique=True), max_length=100),
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='winRate',
            field=models.FloatField(default=0.0),
        ),
    ]
